[workspace]
members = [
    "shader_frg_basic_static",
    "shader_frg_basic_time_uniform",
    "shader_frg_basic_time_globals",
    "shader_frg_basic_hot_reload",
    "shader_frg_basic_dynamic_update",
]
resolver = "2"